services:
  cache:
    image: redis:6.2-alpine
    restart: always
    container_name: redis-local
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    volumes:
      - cache:/data

  app:
    image: node:18-alpine
    container_name: chat
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      SESSION_SECRET: CAT
      REDIS_PORT: 6379
      REDIS_PASS: password
      REDIS_HOST: cache
    
volumes:
  cache:
    driver: local